# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    env_file:
      - .env
    networks:
      - mynetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
